Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'web'

    web.vm.network "public_network", bridge: "wlo1"
    web.vm.provision :shell, path: "bootstrap.sh"
    web.vm.network :forwarded_port, guest: 80, host: 4567



    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = 'db'

    db.vm.network "public_network", bridge: "wlo1"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
    end
  end
end
